import {withDemoBindings} from '../../../lib/runtime/request-bindings';
import {trackerContext} from '../tracker/route';
export const dynamic='force-dynamic';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
type Message={id:string;studentId:string;senderRole:'teacher'|'student';body:string;createdAt:string;readByTeacher:number;readByStudent:number};
const fields='id,student_id AS studentId,sender_role AS senderRole,body,created_at AS createdAt,read_by_teacher AS readByTeacher,read_by_student AS readByStudent';
async function context(req:Request){const c=await trackerContext(req);if(!c)return null;if(!c.teacher&&!c.student)return null;const requested=new URL(req.url).searchParams.get('studentId');const sid=c.teacher?requested:c.student!.id;if(!c.teacher&&requested&&requested!==sid)return null;if(sid&&!c.state.students.some(s=>s.id===sid))return null;return{...c,sid,messageSid:c.datasetId+':'+sid,prefix:c.datasetId+':',role:c.teacher?'teacher':'student'};}
async function GETHandler(req:Request){try{const c=await context(req);if(!c)return response({error:'Bu sohbete erişiminiz yok.'},403);const readField=c.teacher?'read_by_teacher':'read_by_student',other=c.teacher?'student':'teacher';const result=await c.db.prepare(`SELECT student_id AS studentId,COUNT(*) AS count FROM messages WHERE substr(student_id,1,?)=? AND sender_role=? AND ${readField}=0${c.teacher?'':' AND student_id=?'} GROUP BY student_id`).bind(...(c.teacher?[c.prefix.length,c.prefix,other]:[c.prefix.length,c.prefix,other,c.messageSid])).all<{studentId:string;count:number}>();const unread=new Map(result.results.map(r=>[r.studentId,r.count]));const conversations=c.state.students.filter(s=>c.teacher||s.id===c.sid).map(s=>({studentId:s.id,name:s.name,grade:s.grade,avatarId:s.avatarId,unread:unread.get(c.datasetId+':'+s.id)||0}));if(!c.sid)return response({conversations,messages:[],hasMore:false});let condition='',args:unknown[]=[c.messageSid];const before=new URL(req.url).searchParams.get('before');if(before){const cursor=await c.db.prepare('SELECT created_at,id FROM messages WHERE id=? AND student_id=?').bind(before,c.messageSid).first<{created_at:string;id:string}>();if(!cursor)return response({error:'Mesaj bulunamadı.'},400);condition=' AND (created_at < ? OR (created_at = ? AND id < ?))';args.push(cursor.created_at,cursor.created_at,cursor.id);}
const rows=await c.db.prepare(`SELECT ${fields} FROM messages WHERE student_id=?${condition} ORDER BY created_at DESC,id DESC LIMIT 101`).bind(...args).all<Message>();return response({conversations,messages:rows.results.slice(0,100).reverse().map(m=>({...m,studentId:c.sid})),hasMore:rows.results.length>100});}catch(e){console.error(e);return response({error:'Sohbet yüklenemedi. Yeniden deneyin.'},503);}}
async function POSTHandler(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return response({error:'Geçersiz istek.'},403);const c=await context(req);if(!c||!c.sid)return response({error:'Bu sohbete erişiminiz yok.'},403);const payload=await req.json() as {action?:string;id?:string;body?:string};if(payload.action==='read'){if(!payload.id)return response({error:'Mesaj seçilmedi.'},400);const msg=await c.db.prepare('SELECT created_at FROM messages WHERE id=? AND student_id=?').bind(payload.id,c.messageSid).first<{created_at:string}>();if(!msg)return response({error:'Mesaj bulunamadı.'},404);const readField=c.teacher?'read_by_teacher':'read_by_student';await c.db.prepare(`UPDATE messages SET ${readField}=1 WHERE student_id=? AND sender_role=? AND ${readField}=0 AND created_at<=?`).bind(c.messageSid,c.teacher?'student':'teacher',msg.created_at).run();return response({ok:true});}
if(typeof payload.body!=='string'||!payload.body.trim()||payload.body.trim().length>2000||typeof payload.id!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(payload.id))return response({error:'Mesaj 1–2000 karakter arasında olmalı.'},400);const body=payload.body.trim(),createdAt=new Date().toISOString();await c.db.prepare('INSERT OR IGNORE INTO messages (id,student_id,sender_role,body,created_at,read_by_teacher,read_by_student) VALUES (?,?,?,?,?,?,?)').bind(payload.id,c.messageSid,c.role,body,createdAt,c.teacher?1:0,c.teacher?0:1).run();const msg=await c.db.prepare(`SELECT ${fields} FROM messages WHERE id=?`).bind(payload.id).first<Message>();if(!msg||msg.studentId!==c.messageSid||msg.senderRole!==c.role||msg.body!==body)return response({error:'Mesaj zaten kullanılmış. Yeniden gönderin.'},409);return response({message:{...msg,studentId:c.sid}});}catch(e){console.error(e);return response({error:'Mesaj gönderilemedi; yazdığınız metin korunuyor.'},503);}}

export const GET=withDemoBindings(GETHandler);
export const POST=withDemoBindings(POSTHandler);
