import {withDemoBindings} from '../../../lib/runtime/request-bindings';
import {env} from 'cloudflare:workers';
import {trackerContext} from '../tracker/route';
export const dynamic='force-dynamic';
async function POSTHandler(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Geçersiz istek.'},{status:403});const c=await trackerContext(req);if(!c)return Response.json({error:'Giriş yapın.'},{status:401});const sid=new URL(req.url).searchParams.get('studentId');if(!sid||!c.state.students.some(s=>s.id===sid)||(!c.teacher&&c.student?.id!==sid))return Response.json({error:'Yetkiniz yok.'},{status:403});if(!env.BUCKET)throw Error('Fotoğraf alanı kullanılamıyor');const bytes=await req.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>6*1024*1024)return Response.json({error:'Fotoğraf en fazla 6 MB olabilir.'},{status:400});const b=new Uint8Array(bytes);const type=b[0]===255&&b[1]===216&&b[2]===255?'image/jpeg':b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71?'image/png':b[0]===82&&b[1]===73&&b[2]===70&&b[3]===70&&b[8]===87&&b[9]===69&&b[10]===66&&b[11]===80?'image/webp':null;if(!type)return Response.json({error:'JPEG, PNG veya WebP fotoğraf seçin.'},{status:400});const key=crypto.randomUUID();await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:type},customMetadata:{studentId:sid,datasetId:c.datasetId}});return Response.json({key});}catch(e){console.error(e);return Response.json({error:'Fotoğraf yüklenemedi. Tekrar deneyin.'},{status:503})}}
async function GETHandler(req:Request){try{const c=await trackerContext(req);if(!c)return new Response('Giriş yapın',{status:401});const key=new URL(req.url).searchParams.get('key');if(!key||!/^[-a-f0-9]{36}$/.test(key))return new Response('Bulunamadı',{status:404});if(!env.BUCKET)throw Error('Fotoğraf alanı kullanılamıyor');const file=await env.BUCKET.get(key);if(!file)return new Response('Bulunamadı',{status:404});if(file.customMetadata?.datasetId!==c.datasetId)return new Response('Yetkiniz yok',{status:403});if(!c.teacher&&(!c.student||(file.customMetadata?.studentId!==c.student.id&&!c.state.books.some(b=>(b.shared||b.studentIds.includes(c.student!.id))&&b.photoKey===key&&(b.grades||[b.grade]).includes(c.student!.grade)))))return new Response('Yetkiniz yok',{status:403});return new Response(file.body,{headers:{'Content-Type':file.httpMetadata?.contentType||'image/jpeg','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}catch(e){console.error(e);return new Response('Fotoğraf açılamadı',{status:503})}}

export const POST=withDemoBindings(POSTHandler);
export const GET=withDemoBindings(GETHandler);
