'use client';
import type {Student,Log} from '../lib/model';
import {studentCourses,studentQuestionCourses} from '../lib/student-courses';
import {useState} from 'react';
import {curriculum,curriculumYear,curriculumChecked,schoolSubjects,questionSubjects,topicOptions} from '../lib/curriculum';
export function TopicField({grade,subject,initial='',customTopics=[],onChange}:{grade:number;subject:string;initial?:string;customTopics?:string[];onChange?:(value:string)=>void}){
 const official=topicOptions(grade,subject),extra=[...new Set(customTopics)].filter(t=>t&&!official.includes(t)),options=[...official,...extra];
 const [chosen,setChosen]=useState(options.includes(initial)?initial:initial?'other':''),[custom,setCustom]=useState(options.includes(initial)?'':initial);
 return <div className="field"><label htmlFor="study-topic">Konu / öğrenme alanı</label><select id="study-topic" name={chosen==='other'?undefined:'topic'} value={chosen} required onChange={e=>{setChosen(e.target.value);onChange?.(e.target.value)}}><option value="">{grade}. sınıf konusu seç</option>{curriculum[String(grade)]?.[subject]?.units.map(u=><optgroup key={u.name} label={u.name}><option value={u.name}>{u.name} (genel)</option>{u.topics.map(t=><option key={t} value={u.name+' / '+t}>{t}</option>)}</optgroup>)}{extra.length>0&&<optgroup label="Ek konu başlıkları">{extra.map(t=><option key={t}>{t}</option>)}</optgroup>}<option value="other">Konum listede yok · elle ekle</option></select><button type="button" className="textButton" onClick={()=>setChosen(chosen==='other'?'':'other')}>{chosen==='other'?'Listeden konu seç':'Konum yok, kendim yazacağım'}</button>{chosen==='other'&&<label className="field"><span>Manuel konu adı</span><input name="topic" value={custom} onChange={e=>setCustom(e.target.value)} maxLength={300} required placeholder="Örn. Tam sayılarla problem çözme"/><small className="formHint">Çalışmayı kaydedince bu konu sonraki soru kayıtlarında da listelenir.</small></label>}<small className="formHint">{grade===8?'Önceki öğretim programı':'Türkiye Yüzyılı Maarif Modeli'} · {curriculumYear}.</small></div>
}
export default function CurriculumBrowser({grade,locked=false,onStudy,student,studyLogs=[],settings}:{grade:number;locked?:boolean;onStudy:(subject:string,topic:string)=>void;student?:Student;studyLogs?:Log[];settings?:React.ReactNode}){
 const [selectedGrade,setGrade]=useState(grade),[selectedSubject,setSubject]=useState('Matematik'),[search,setSearch]=useState('');const personal=selectedGrade===grade,subjects=personal&&student?studentCourses(student):schoolSubjects(selectedGrade),subject=subjects.includes(selectedSubject)?selectedSubject:subjects[0]||'',course=curriculum[String(selectedGrade)]?.[subject],q=search.trim().toLocaleLowerCase('tr'),isExtra=personal&&student?.extraCourses?.includes(subject),customTopics=[...new Set([...(student?.courseTopics?.[subject]||[]),...studyLogs.filter(l=>l.subject===subject).map(l=>l.topic)])],filtered=course?.units.map(u=>({...u,topics:q&&!u.name.toLocaleLowerCase('tr').includes(q)?u.topics.filter(t=>t.toLocaleLowerCase('tr').includes(q)):u.topics})).filter(u=>!q||u.name.toLocaleLowerCase('tr').includes(q)||u.topics.length)||[],canStudy=personal&&studentQuestionCourses(student||{grade} as Student).includes(subject);
 return <>{settings}<div className="toolbar">{locked?<strong>{grade}. sınıf konularım</strong>:<select aria-label="Konu kapsamı sınıfı" value={selectedGrade} onChange={e=>{setGrade(Number(e.target.value));setSubject('Matematik')}}>{[6,7,8].map(g=><option key={g} value={g}>{g}. sınıf</option>)}</select>}<select aria-label="Ders kapsamı" value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select><input placeholder="Konu ara…" aria-label="Müfredat konusu ara" value={search} onChange={e=>setSearch(e.target.value)}/></div>{isExtra?<section className="panel extraCoursePanel"><div className="panelHead"><div><span className="badge">Okul / ek ders</span><h2>{subject}</h2></div>{canStudy&&<button className="primary" onClick={()=>onStudy(subject,customTopics[0]||'Karışık test')}>Çalışma ekle</button>}</div><p className="panelText">Bu ders için konuları öğretmenin ekleyebilir. Çalışma kaydında kendi konu başlığını da yazabilirsin.</p>{customTopics.length?<ul className="topicList">{customTopics.filter(t=>!q||t.toLocaleLowerCase('tr').includes(q)).map(t=><li key={t}><span>{t}</span>{canStudy&&<button className="textButton" onClick={()=>onStudy(subject,t)}>Çalışma ekle</button>}</li>)}</ul>:<p className="panelText muted">Henüz konu başlığı yok. İlk çalışmanı kaydederken konunu yaz.</p>}</section>:<><details className="curriculumIntro curriculumSourceNote"><summary>{selectedGrade}. sınıf · {subject} · Konu listesi hakkında</summary><div><p>{curriculumYear} · {selectedGrade===8?'Önceki öğretim programı':'Türkiye Yüzyılı Maarif Modeli'} · Kaynak kontrolü: {curriculumChecked}</p><p>Ünite ve tema başlıkları MEB programlarına dayanır. Alt başlıklar çalışma takibi için düzenlenmiştir. Okulunun işleme sırası değişebilir.</p>{course&&<a className="secondary" href={course.source} target="_blank" rel="noreferrer">MEB kaynağını aç</a>}</div></details><div className="curriculumUnits">{filtered.map(u=><section className="panel" key={u.name}><div className="panelHead"><h2>{u.name}</h2><a href={u.url} target="_blank" rel="noreferrer">Kaynak</a></div>{u.topics.length?<ul className="topicList">{u.topics.map(t=><li key={t}><span>{t}</span>{canStudy&&<button className="textButton" onClick={()=>onStudy(subject,u.name+' / '+t)}>Çalışma ekle</button>}</li>)}</ul>:<p className="muted">Bu başlığı seçerek çalışmanı kaydedebilirsin.</p>}{canStudy&&<button className="secondary" onClick={()=>onStudy(subject,u.name)}>Bu üniteye çalışma ekle</button>}</section>)}</div>{!filtered.length&&<p className="empty">Aradığın konu bulunamadı.</p>}</>}</>
}
