'use client';
import {useEffect,useState,type Ref} from 'react';
import {Plus,Pause,Play,Sparkles,Star} from 'lucide-react';
import type {Student,Exam} from '../lib/model';
import {studentInspiration} from '../lib/student-inspiration';
import {Avatar} from './student-journey';
export default function HomeInspiration({student,exams,days,celebrateId='',recordRef,onRecord,onAvatar,onProgress}:{student:Student;exams:Exam[];days:number;celebrateId?:string;recordRef:Ref<HTMLButtonElement>;onRecord:()=>void;onAvatar:()=>void;onProgress:()=>void}){
 const [moving,setMoving]=useState(false),[replay,setReplay]=useState(0),[burst,setBurst]=useState(false),[celebrations,setCelebrations]=useState(0),[reduced,setReduced]=useState(true);
 const {latest,before,delta,improved,visual,title,message,gains}=studentInspiration(student,exams),names={rocket:'Yıldızlara doğru',sail:'Yeni ufuklara doğru',star:'Kendi ışığını keşfet',fireworks:'Emeğini kutla'};
 useEffect(()=>{const pref=window.matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{setReduced(pref.matches);if(pref.matches){setMoving(false);setBurst(false)}};change();pref.addEventListener('change',change);if(!pref.matches)setMoving(true);const timer=setTimeout(()=>setMoving(false),8000);return()=>{clearTimeout(timer);pref.removeEventListener('change',change)}},[student.id,visual,replay,celebrateId]);
 useEffect(()=>{if(reduced||!improved||!(celebrations>0||celebrateId&&celebrateId===latest?.id))return;setBurst(true);const timer=setTimeout(()=>setBurst(false),2400);return()=>clearTimeout(timer)},[reduced,improved,celebrations,celebrateId,latest?.id]);
 function pause(){setMoving(false);setBurst(false)}
 function celebrate(){setReplay(n=>n+1);setCelebrations(n=>n+1)}
 return <section className={'homeInspiration inspiration-'+visual} aria-labelledby="home-inspiration-title" data-visual={visual}><div className="inspirationCopy"><span className="inspirationEyebrow">{names[visual]}</span><h2 id="home-inspiration-title">{title}</h2><p>{message}</p>{gains.length>0&&<div className="inspirationGains">{gains.slice(0,2).map(g=><span key={g.subject}><Star size={14} fill="currentColor"/>{g.subject} +{new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(g.delta)} net</span>)}</div>}</div><div className={'inspirationArt motion-'+visual+(moving?' isMoving':'')}><img className="inspirationScene" src={'/motion/'+visual+'.webp'} width={560} height={560} alt={visual==='rocket'?'Keşfe doğru yükselen roket':visual==='sail'?'Yoluna devam eden yelkenli':visual==='star'?'Parlayan yıldız':'Emeğini kutlayan renkli havai fişekler'} fetchPriority="high"/><button className="inspirationCompanion" onClick={onAvatar} aria-label="Yol arkadaşımı ve temamı değiştir"><Avatar id={student.avatarId} size={58}/></button>{burst&&<img className="inspirationCelebration" src={'/motion/'+(visual==='fireworks'?'fireworks':'star')+'.webp'} width={560} height={560} alt="" aria-hidden="true"/>}<button type="button" className="inspirationMotionControl" onClick={()=>moving?pause():setReplay(n=>n+1)} aria-label={moving?'Animasyonu durdur':'Animasyonu yeniden oynat'}>{moving?<Pause size={14}/>:<Play size={14}/>}<span>{moving?'Durdur':'Oynat'}</span></button></div><div className="inspirationFooter"><div className="inspirationActions"><button className="primary" ref={recordRef} onClick={onRecord}><Plus size={20}/>Çalışmamı kaydet</button>{improved&&<button className="inspirationCelebrate" onClick={celebrate}><Sparkles size={17}/>Kutla</button>}<button className="inspirationProgress" onClick={onProgress}>Gelişimime bak</button></div><span className="inspirationWeek">{days?`Bu hafta ${days} farklı gün çalışmanı kaydettin.`:'Bugün küçük bir adımla başlayabilirsin.'}</span></div>{latest&&before&&<details className="inspirationComparison"><summary>Deneme karşılaştırması</summary><p>{before.name} ({before.date}) ve {latest.name} ({latest.date}) · {new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(delta||0)} net değişim. Aynı tür, soru dağılımı ve zorluk etiketi karşılaştırıldı. Denemelerin gerçek güçlüğü yine de değişebilir.</p></details>}</section>
}
