'use client';
import {useEffect,useState,useRef} from 'react';
import {MessageCircle,Send,X,RefreshCw,ChevronUp} from 'lucide-react';
import {Avatar} from './student-journey';
import type {Student} from '../lib/model';
type Message={id:string;studentId:string;senderRole:string;body:string;createdAt:string;readByTeacher:number;readByStudent:number};
type ChatData={error?:string;conversations:Conversation[];messages:Message[];hasMore:boolean};
type Conversation={studentId:string;name:string;grade:number;avatarId?:string;unread:number};
export default function MessageCenter({role,sid,students}:{role:string;sid:string;students:Student[]}){
 const teacher=role==='teacher', [open,setOpen]=useState(false),[chatSid,setChatSid]=useState(sid),[messages,setMessages]=useState<Message[]>([]),[conversations,setConversations]=useState<Conversation[]>([]),[drafts,setDrafts]=useState<Record<string,string>>({}),[error,setError]=useState(''),[sending,setSending]=useState(false),[loading,setLoading]=useState(false),[hasMore,setHasMore]=useState(false),[older,setOlder]=useState(false),[retry,setRetry]=useState(0);const bottom=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),active=useRef(chatSid),nonce=useRef<Record<string,{text:string;id:string}>>({});active.current=chatSid;
 const url=(studentId:string,before?:string)=>{const q=new URLSearchParams(window.location.search);q.set('studentId',studentId);if(before)q.set('before',before);return '/api/messages?'+q.toString()};
 useEffect(()=>{setChatSid(sid);setError('')},[sid]);
 useEffect(()=>{let stopped=false,first=true,fetching=false;const controller=new AbortController();setMessages([]);setOlder(false);setHasMore(false);setError('');setLoading(open);async function refresh(){if(document.hidden||fetching)return;fetching=true;try{const r=await fetch(url(chatSid),{cache:'no-store',signal:controller.signal});const data=await r.json() as ChatData;if(!r.ok)throw Error(data.error||'Sohbet yüklenemedi.');if(stopped)return;setConversations(data.conversations);if(first){setHasMore(data.hasMore);first=false;}setMessages(previous=>{const map=new Map(previous.map(m=>[m.id,m]));for(const m of data.messages)map.set(m.id,m);return [...map.values()].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))});setError('');const last=data.messages.at(-1);if(open&&last&&data.conversations.some((c:Conversation)=>c.studentId===chatSid&&c.unread>0)){const rr=await fetch(url(chatSid),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'read',id:last.id}),signal:controller.signal});if(rr.ok&&!stopped)setConversations(data.conversations.map((c:Conversation)=>c.studentId===chatSid?{...c,unread:0}:c));}}catch(e){if(!stopped&&!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'Sohbet yüklenemedi.')}finally{fetching=false;if(!stopped)setLoading(false)}}void refresh();const timer=setInterval(()=>void refresh(),open?4000:12000);return()=>{stopped=true;controller.abort();clearInterval(timer)}},[chatSid,open,retry]);
 useEffect(()=>{if(open&&!older)bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages,open,older]);
 useEffect(()=>{if(!open)return;input.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);e.stopPropagation()}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[open]);
 async function send(e:React.FormEvent){e.preventDefault();const target=chatSid,text=(drafts[target]||'').trim();if(!text||sending)return;const id=nonce.current[target]?.text===text?nonce.current[target].id:crypto.randomUUID();nonce.current[target]={text,id};setSending(true);setError('');try{const r=await fetch(url(target),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,body:text})});const data=await r.json() as {error?:string;message:Message};if(!r.ok)throw Error(data.error||'İşlem tamamlanamadı.');setDrafts(d=>({...d,[target]:d[target]?.trim()===text?'':d[target]}));delete nonce.current[target];if(active.current===target){setOlder(false);setMessages(ms=>[...ms.filter(m=>m.id!==id),data.message]);}}catch(e){if(active.current===target)setError(e instanceof Error?e.message:'Mesaj gönderilemedi.')}finally{setSending(false)}}
 async function loadOlder(){if(!messages[0])return;setLoading(true);try{const target=chatSid,r=await fetch(url(target,messages[0].id),{cache:'no-store'}),data=await r.json() as ChatData;if(!r.ok)throw Error(data.error||'İşlem tamamlanamadı.');if(active.current!==target)return;setOlder(true);setMessages(ms=>{const map=new Map([...data.messages,...ms].map(m=>[m.id,m]));return [...map.values()]});setHasMore(data.hasMore);}catch(e){setError(e instanceof Error?e.message:'Mesajlar yüklenemedi.')}finally{setLoading(false)}}
 const unread=conversations.reduce((n,c)=>n+c.unread,0),person=students.find(s=>s.id===chatSid);return <div className="messageCenter">{open&&<section className="chatPanel" role="dialog" aria-modal="false" aria-label={teacher?'Öğrenci mesajları':'Öğretmenimle mesajlaşma'}><div className="chatHeader"><Avatar id={person?.avatarId} size={38}/><div><strong>{teacher?'Öğrenci mesajları':'Öğretmenim'}</strong><small>{teacher?person?.name:'Sorunu yaz, birlikte çözelim.'}</small></div><button className="iconButton" aria-label="Mesajları kapat" onClick={()=>setOpen(false)}><X size={21}/></button></div>{teacher&&<label className="chatSelect"><span>Öğrenci</span><select aria-label="Sohbet öğrencisi" value={chatSid} onChange={e=>setChatSid(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.name}{conversations.find(c=>c.studentId===s.id)?.unread?' · '+conversations.find(c=>c.studentId===s.id)!.unread+' yeni':''}</option>)}</select></label>}<div className="chatMessages" aria-live="polite" aria-relevant="additions">{hasMore&&<button className="textButton" disabled={loading} onClick={loadOlder}><ChevronUp size={15}/>Önceki mesajlar</button>}{loading&&!messages.length?<p className="muted">Sohbet yükleniyor…</p>:!messages.length&&<div className="chatEmpty"><MessageCircle size={30}/><strong>{teacher?'Birlikte bir adım atalım':'Aklındaki soruyu paylaş'}</strong><p>{teacher?'Öğrencine planı veya çalışmaları hakkında yazabilirsin.':'Bir konu, kitap veya çalışma planı hakkında öğretmenine sorabilirsin.'}</p></div>}{messages.map(m=><div key={m.id} className={'chatBubble '+(m.senderRole===role?'ownMessage':'')}><span>{m.senderRole===role?'Sen':m.senderRole==='teacher'?'Öğretmen':person?.name.split(' ')[0]||'Öğrenci'}</span><p>{m.body}</p><small>{new Date(m.createdAt).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}{m.senderRole===role&&(teacher?m.readByStudent:m.readByTeacher)?' · Okundu':''}</small></div>)}<div ref={bottom}/></div>{error&&<div className="chatError" role="alert">{error}<button className="textButton" onClick={()=>setRetry(n=>n+1)}><RefreshCw size={14}/>Yeniden dene</button></div>}<form className="chatComposer" onSubmit={send}><textarea ref={input} aria-label="Mesajın" placeholder={teacher?'Öğrencine yaz…':'Öğretmenime sor…'} value={drafts[chatSid]||''} onChange={e=>setDrafts(d=>({...d,[chatSid]:e.target.value}))} maxLength={2000} rows={2}/><button className="primary" type="submit" disabled={sending||!(drafts[chatSid]||'').trim()} aria-label="Mesajı gönder"><Send size={19}/></button></form><p className="chatHint">Sohbet açıkken mesajlar birkaç saniyede yenilenir.</p></section>}<button className="chatLauncher" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Öğretmen ve öğrenci mesajlaşmasını aç"><MessageCircle size={23}/><span>{teacher?'Mesajlar':'Öğretmenime sor'}</span>{unread>0&&<strong>{unread}</strong>}</button></div>;
}
