'use client';
import {useState} from 'react';
import type {Book,Log} from '../lib/model';
import {TopicField} from './curriculum-browser';
export default function QuickStudyForm({books,logs,grade,subjects,subject,onSubject,editing,initialTopic,customTopics=[]}:{books:Book[];logs:Log[];grade:number;subjects:string[];subject:string;onSubject:(s:string)=>void;editing:Log|null;initialTopic:string;customTopics?:string[]}){
 const matching=books.filter(b=>b.subject===subject||b.subject==='Tüm dersler'),recent=[...logs].reverse().find(l=>l.subject===subject&&matching.some(b=>b.id===l.bookId));
 const [bookId,setBookId]=useState(editing&&matching.some(b=>b.id===editing.bookId)?editing.bookId:recent?.bookId||matching[0]?.id||'unlisted');
 const [questions,setQuestions]=useState(editing?String(editing.correct+editing.wrong+editing.blank):''),[wrong,setWrong]=useState(String(editing?.wrong||0)),[blank,setBlank]=useState(String(editing?.blank||0));
 const n=Number(questions),w=Number(wrong),b=Number(blank),correct=n-w-b,invalid=correct<0;
 const selectedRecent=[...logs].reverse().find(l=>l.subject===subject&&l.bookId===bookId);const initial=initialTopic||(editing?.subject===subject&&editing.bookId===bookId?editing.topic:selectedRecent?.topic||'Karışık test');
 return <><div className="quickStudyFields"><label className="field"><span>Kaynağım · {grade}. sınıf</span><select name="bookId" value={bookId} onChange={e=>{const id=e.target.value;setBookId(id);const book=books.find(b=>b.id===id);if(book&&subjects.includes(book.subject))onSubject(book.subject)}}>{books.map(b=><option key={b.id} value={b.id}>{b.name} · {b.publisher}</option>)}<option value="unlisted">Kitap dışı / kaynak belirtilmemiş</option></select>{!books.length&&<small>Kitabını Kaynaklarım’a eklediğinde burada görünür.</small>}</label><label className="field"><span>Ders</span><select value={subject} onChange={e=>{onSubject(e.target.value);const options=books.filter(b=>b.subject===e.target.value||b.subject==='Tüm dersler');setBookId(options[0]?.id||'unlisted')}}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label></div>
 <div className="quickCounts"><label className="field"><span>Toplam soru</span><input autoFocus name="questionCount" type="number" inputMode="numeric" min="1" max="100000" step="1" placeholder="Örn. 20" value={questions} onChange={e=>setQuestions(e.target.value)} required/></label><label className="field"><span>Yanlış</span><input name="wrong" type="number" inputMode="numeric" min="0" max={n||100000} step="1" value={wrong} onChange={e=>setWrong(e.target.value)} onFocus={e=>e.target.select()} required/></label><label className="field"><span>Boş</span><input name="blank" type="number" inputMode="numeric" min="0" max={n||100000} step="1" value={blank} onChange={e=>setBlank(e.target.value)} onFocus={e=>e.target.select()} required/></label><div className={'correctResult '+(invalid?'invalid':'')} role="status"><span>Doğru</span><strong>{questions&&!invalid?correct:'—'}</strong><small>Otomatik hesaplanır</small></div></div><input type="hidden" name="correct" value={Math.max(0,correct)}/>{invalid&&<p className="alert" role="alert">Yanlış ve boş toplamı, toplam soru sayısını aşamaz.</p>}
 <TopicField key={subject+bookId} grade={grade} subject={subject} initial={initial} customTopics={['Karışık test',...customTopics,...logs.filter(l=>l.subject===subject).map(l=>l.topic)]}/>
 <details className="studyExtras" open={!!editing?.note||!!editing?.minutes||!!editing?.testLabel}><summary>Test adı, süre ve not (isteğe bağlı)</summary><label className="field"><span>Test adı / numarası</span><input name="testLabel" defaultValue={editing?.testLabel||''} placeholder="Örn. Test 4 · Sayfa 32" maxLength={200}/></label><label className="field"><span>Süre (dakika)</span><input name="minutes" type="number" inputMode="numeric" min="0" max="1440" defaultValue={editing?.minutes||0}/></label><label className="field"><span>Not</span><textarea name="note" defaultValue={editing?.note||''} maxLength={2000} rows={2}/></label></details></>;
}
