'use client';
import {useState,useRef,useEffect} from 'react';
import {BookOpen,Plus,PenLine,Trash2,Check,Clock} from 'lucide-react';
import type {State,ReadingBook} from '../lib/model';
import {readingDays,readingStats,validReading} from '../lib/planning';
const nice=(d:string)=>d?new Date(d+'T12:00:00').toLocaleDateString('tr-TR',{day:'numeric',month:'short',year:'numeric'}):'—';
export default function ReadingTracker({state,sid,busy,onSave,reference}:{state:State;sid:string;busy:boolean;onSave:(state:State)=>Promise<boolean>;reference:string}){
 const [date,setDate]=useState(reference),[filter,setFilter]=useState('Tümü'),[show,setShow]=useState(false),[edit,setEdit]=useState<ReadingBook|null>(null),[status,setStatus]=useState<ReadingBook['status']>('Listemde'),[message,setMessage]=useState('');const formRef=useRef<HTMLFormElement>(null);
 const grade=state.students.find(s=>s.id===sid)?.grade||7,recommendations=(state.readingRecommendations||[]).filter(r=>r.grades.includes(grade));
 const books=(state.reading||[]).filter(b=>b.studentId===sid),stats=readingStats(books,date),shown=books.filter(b=>filter==='Tümü'||b.status===filter);
 useEffect(()=>{if(show)formRef.current?.scrollIntoView({behavior:'smooth',block:'center'})},[show]);
 function open(book?:ReadingBook){setEdit(book||null);setStatus(book?.status||'Listemde');setShow(true);setMessage('')}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),get=(k:string)=>String(f.get(k)||'').trim(),pages=Number(get('totalPages'));const item:ReadingBook={id:edit?.id||crypto.randomUUID(),studentId:sid,title:get('title'),author:get('author'),totalPages:pages,currentPage:status==='Bitirdim'?pages:status==='Listemde'?0:Number(get('currentPage')),status,started:status==='Listemde'?'':get('started'),finished:status==='Bitirdim'?get('finished'):'',note:get('note')};if(!validReading(item)){setMessage('Sayfa ilerlemesi kitabın sayfa sayısını aşamaz. Başlangıç/bitiş tarihlerini kontrol et.');return}if(await onSave({...state,reading:[...(state.reading||[]).filter(b=>b.id!==item.id),item]})){setShow(false);setMessage('')}}
 async function remove(book:ReadingBook){if(window.confirm('Bu kitabı okuma listesinden silmek istiyor musun?'))await onSave({...state,reading:(state.reading||[]).filter(b=>b.id!==book.id)});}
 return <><div className="toolbar"><label className="readingDate">Özet tarihi <input aria-label="Okuma özeti tarihi" type="date" max={reference} value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>open()}><Plus size={17}/>Okuma listesine kitap ekle</button></div><div className="metrics readingMetrics">{[['Bu hafta',stats.week],['Bu ay',stats.month],['Bu yıl',stats.year]].map(([label,list])=><div className="metric" key={String(label)}><span>{String(label)} biten</span><strong>{(list as ReadingBook[]).length}<em> kitap</em></strong><small>{(list as ReadingBook[]).reduce((n,b)=>n+b.totalPages,0)} sayfalık kitap tamamlandı</small></div>)}<div className="metric"><span>Şu an okunuyor</span><strong>{stats.current.length}<em> kitap</em></strong><small>{books.filter(b=>b.status==='Listemde').length} kitap sırada</small></div></div><p className="readingFootnote">Biten kitaplar bitiş tarihine göre sayılır; günlük “Kitap Okuma” aktivitesi tek başına kitap bitirmek sayılmaz. Süre, başlangıç ile bitiş arasındaki takvim günüdür.</p>
 {show&&<form className="panel readingForm" ref={formRef} onSubmit={submit} key={edit?.id||'new'}><div className="panelHead"><h2>{edit?'Kitabı ve ilerlemeyi düzenle':'Okuma listene ekle'}</h2><button className="textButton" type="button" onClick={()=>setShow(false)}>Vazgeç</button></div><div className="formGrid"><label className="field"><span>Kitabın adı</span><input name="title" defaultValue={edit?.title||''} maxLength={200} required/></label><label className="field"><span>Yazar (isteğe bağlı)</span><input name="author" defaultValue={edit?.author||''} maxLength={150}/></label><label className="field"><span>Toplam sayfa</span><input name="totalPages" type="number" min={1} max={100000} step={1} defaultValue={edit?.totalPages||''} required/></label><label className="field"><span>Okuma durumu</span><select value={status} onChange={e=>setStatus(e.target.value as ReadingBook['status'])}><option>Listemde</option><option>Okuyorum</option><option>Bitirdim</option></select></label>{status==='Okuyorum'&&<label className="field"><span>Ulaştığın sayfa</span><input name="currentPage" type="number" min={0} max={100000} step={1} defaultValue={edit?.currentPage||0} required/></label>}{status!=='Listemde'&&<label className="field"><span>Başlama tarihi</span><input name="started" type="date" max={reference} defaultValue={edit?.started||reference} required/></label>}{status==='Bitirdim'&&<label className="field"><span>Bitirme tarihi</span><input name="finished" type="date" max={reference} defaultValue={edit?.finished||reference} required/></label>}</div><label className="field"><span>Kitap hakkında notun</span><textarea name="note" defaultValue={edit?.note||''} placeholder="En sevdiğin bölüm, yeni öğrendiğin bir şey…" maxLength={2000}/></label>{message&&<p className="alert" role="alert">{message}</p>}<button className="primary" type="submit" disabled={busy}>{busy?'Kaydediliyor…':'Kitabı kaydet'}</button></form>}
 {recommendations.length>0&&<section className="readingRecommendations"><div className="homeSectionHead"><h2>Öğretmeninden kitap önerileri</h2><span className="badge">{grade}. sınıf</span></div><div className="recommendationBooks">{recommendations.map(r=>{const added=books.some(b=>b.recommendationId===r.id||(b.title===r.title&&b.author===r.author));return <article key={r.id}><BookOpen size={22}/><div><strong>{r.title}</strong><p>{r.author||'Yazar belirtilmedi'} · {r.totalPages} sayfa</p></div><button className={added?'textButton':'secondary'} disabled={busy||added} onClick={()=>void onSave({...state,reading:[...(state.reading||[]),{id:crypto.randomUUID(),recommendationId:r.id,studentId:sid,title:r.title,author:r.author,totalPages:r.totalPages,currentPage:0,status:'Listemde',started:'',finished:'',note:''}]})}>{added?'Listemde':'Listeme ekle'}</button></article>})}</div></section>}
 <div className="toolbar"><div className="segmented readingFilters">{['Tümü','Okuyorum','Listemde','Bitirdim'].map(s=><button key={s} className={filter===s?'chosen':''} onClick={()=>setFilter(s)}>{s}</button>)}</div><span className="muted">{shown.length} kitap</span></div><div className="readingGrid">{shown.map(b=>{const days=readingDays(b,reference),percent=Math.round(b.currentPage/b.totalPages*100);return <article className={'panel readingCard '+(b.status==='Okuyorum'?'currentlyReading':'')} key={b.id}><div className="readingCardHead"><span className="readingIcon"><BookOpen size={25}/></span><span className="badge">{b.status==='Bitirdim'?<><Check size={14}/>Bitirdim</>:b.status}</span></div><h2>{b.title}</h2><p className="muted">{b.author||'Yazar eklenmedi'}</p><div className="readingProgress"><strong>{b.currentPage} / {b.totalPages} sayfa</strong><span>%{percent}</span></div><div className="progress"><i style={{width:percent+'%'}}/></div><div className="readingDetail"><span>Başlangıç<strong>{nice(b.started)}</strong></span><span>{b.status==='Bitirdim'?'Bitiş':'Okuma süreci'}<strong>{b.finished?nice(b.finished):days===null?'Henüz başlamadı':`${days}. gününde`}</strong></span></div>{days!==null&&<p className="readingDuration"><Clock size={16}/>{b.status==='Bitirdim'?`${days} takvim gününde tamamlandı`:`Başlangıçtan bu yana ${days} takvim günü`}</p>}{b.note&&<p className="readingNote">{b.note}</p>}<div className="bookBottom"><button className="secondary" disabled={busy} onClick={()=>open(b)}><PenLine size={15}/>{b.status==='Okuyorum'?'İlerlememi güncelle':'Kitabı düzenle'}</button><button className="iconButton" disabled={busy} aria-label={b.title+' kitabını sil'} onClick={()=>remove(b)}><Trash2 size={17}/></button></div></article>})}</div>{!shown.length&&<div className="empty"><BookOpen size={30}/><h3>Okuma yolculuğuna bir kitap ekle</h3><p>Okuyacağın, okuduğun ve bitirdiğin kitapları aynı listede takip et.</p><button className="primary" onClick={()=>open()}>Kitap ekle</button></div>}</>;
}
