'use client';
import {useEffect,useState} from 'react';
import {Star,Sparkles,Pause,Play} from 'lucide-react';
import {avatars,avatarImage} from '../lib/avatars';
import {net,type Student,type Exam} from '../lib/model';
import {examKey} from '../lib/comparison';
export function Avatar({id,size=48}:{id?:string;size?:number}){return <img className="chosenAvatar" src={avatarImage(id)} alt={avatars.find(a=>a.id===id)?.name||'Astro Tilki'} width={size} height={size}/>}
export function AvatarPicker({student}:{student?:Student}){const [id,setId]=useState(student?.avatarId||'fox');const [journey,setJourney]=useState(student?.journey||'rocket');return <div className="avatarPicker"><h3>Bu alan senin. Yol arkadaşını seç!</h3><p>Karakterini daha sonra değiştirebilirsin.</p><input type="hidden" name="avatarId" value={id}/><div className="avatarGrid">{avatars.map(a=><button type="button" key={a.id} className={id===a.id?'avatarOption selected':'avatarOption'} aria-pressed={id===a.id} onClick={()=>setId(a.id)}><Avatar id={a.id} size={84}/><span>{a.name}</span></button>)}</div><h3>Hangi yolculuk sana göre?</h3><input type="hidden" name="journey" value={journey}/><div className="journeyChoices">{[{id:'rocket',name:'Yıldızlara doğru',text:'Her küçük adım yeni bir keşif.'},{id:'sail',name:'Yeni ufuklara',text:'Rüzgâr değişse de yolculuk sürer.'},{id:'star',name:'Işığını keşfet',text:'Küçük adımların da parlasın.'},{id:'fireworks',name:'Renkli bir yolculuk',text:'Emeğini birlikte kutlayalım.'}].map(j=><button type="button" aria-pressed={journey===j.id} key={j.id} className={journey===j.id?'selected':''} onClick={()=>setJourney(j.id as NonNullable<Student['journey']>)}><img src={'/motion/'+j.id+'.webp'} alt=""/><strong>{j.name}</strong><span>{j.text}</span></button>)}</div></div>}
export function JourneyCard({student,exams,celebrateId,onAvatar,onPractice}:{student:Student;exams:Exam[];celebrateId:string;onAvatar:()=>void;onPractice:()=>void}){const [burst,setBurst]=useState(false),[moving,setMoving]=useState(true),[replay,setReplay]=useState(0);const sorted=[...exams].reverse().sort((a,b)=>b.date.localeCompare(a.date));const latest=sorted[0],before=latest?sorted.slice(1).find(e=>examKey(e)===examKey(latest)):undefined;const score=(e:Exam)=>e.rows.reduce((s,r)=>s+net(r),0);const delta=latest&&before?score(latest)-score(before):null;const improved=delta!==null&&delta>0.1;const gains=latest&&before?latest.rows.map(r=>({subject:r.subject,delta:net(r)-net(before.rows.find(b=>b.subject===r.subject)!)})).filter(r=>r.delta>0.1):[];const fmt=(n:number)=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(n);const theme=student.journey||'rocket';
useEffect(()=>{if(!celebrateId||celebrateId!==latest?.id||!improved)return;const start=setTimeout(()=>setBurst(true),0),end=setTimeout(()=>setBurst(false),2400);return()=>{clearTimeout(start);clearTimeout(end)}},[celebrateId,improved,latest?.id]);
useEffect(()=>{setMoving(true);const timer=setTimeout(()=>setMoving(false),8000);return()=>clearTimeout(timer)},[replay,student.id,student.journey,celebrateId]);
function celebrate(){setReplay(n=>n+1);setBurst(true);setTimeout(()=>setBurst(false),2400)}
const visual=delta!==null&&delta<-.1?(theme==='sail'?'sail':'rocket'):improved?(theme==='fireworks'?'fireworks':'star'):theme;const names={rocket:'Yıldızlara yol alan roket',sail:'Denizde yol alan yelkenli',star:'Parlayan yıldız',fireworks:'Renkli havai fişekler'};
return <section className={'journeyCard '+(improved?'celebrating':'travelling')}><div className={'journeyArt motion-'+visual+(moving?' isMoving':'')}><img key={replay} className="scene" src={'/motion/'+visual+'.webp'} alt={names[visual]}/><div className="journeyCompanion"><Avatar id={student.avatarId} size={80}/></div>{burst&&<div className="starBurst" aria-hidden="true">{Array.from({length:12},(_,i)=><Star key={i} style={{'--angle':i*30+'deg','--delay':i%3*70+'ms'} as React.CSSProperties}/>)}</div>}<button className="motionControl" onClick={()=>moving?setMoving(false):setReplay(n=>n+1)} aria-label={moving?'Animasyonu durdur':'Animasyonu yeniden oynat'}>{moving?<Pause size={15}/>:<Play size={15}/>}<span>{moving?'Durdur':'Oynat'}</span></button></div><div className="journeyCopy"><span className="studentEyebrow">{student.name.split(' ')[0].toLocaleUpperCase('tr')}’İN YOLCULUĞU</span><h2>{improved?'İlerlemen parlıyor!':delta!==null&&delta<-.1?'Bir deneme yolculuğun tamamı değil.':delta!==null?'Temelin sağlam, keşfe devam!':'İlk adımınla yolculuk başlar.'}</h2><p>{improved?`Önceki benzer denemene göre ${fmt(delta!)} net ilerledin. Hangi çalışmanın işe yaradığını düşün; onu sürdürebilirsin.`:delta!==null&&delta<-.1?`Bu kez ${fmt(Math.abs(delta))} net daha düşük. Sonuç, hangi konuya dönebileceğini gösteriyor. Bir ders seç; 3 yanlışını incele, sonra 5 soruyla yeniden dene.`:delta!==null?'Benzer denemede netin aynı seviyede. Bugün bir yanlışın nedenini bulmak da ilerlemedir.':'Bir deneme eklediğinde kendi gelişimini burada göreceksin. İlk sonuç, başlangıç noktan olacak.'}</p>{latest&&before&&<small className="comparisonDetail">{before.name} ({before.date}) → {latest.name} ({latest.date}) · {fmt(score(before))} → {fmt(score(latest))} net · Aynı tür, soru dağılımı ve zorluk etiketi; denemelerin güçlüğü yine de değişebilir.</small>}{gains.length>0&&<div className="subjectStars">{gains.map(g=><span key={g.subject}><Star size={18} fill="currentColor"/>{g.subject} +{fmt(g.delta)} net</span>)}</div>}<div className="journeyActions">{improved&&<button className="primary" onClick={celebrate}><Sparkles size={18}/>Yıldızımı kutla</button>}<button className="secondary" onClick={onPractice}>{improved?'Yeni çalışmamı kaydet':'Küçük adımımı kaydet'}</button><button className="textButton" onClick={onAvatar}>Avatarım ve temam</button></div></div></section>}
