'use client';
import {useState,useRef} from 'react';
import {Plus,BookOpen,Check,ClipboardList,PenLine,X,CalendarDays} from 'lucide-react';
import type {State,Student} from '../lib/model';
import {periodBounds} from '../lib/model';
import {daySchedules,scheduleEnd} from '../lib/planning';
import HomeInspiration from './home-inspiration';
export default function StudentHome({state,student,date,celebrateId='',onAvatar,onQuestion,onExam,onReading,onActivity,onPlan,onProgress}:{state:State;student:Student;date:string;celebrateId?:string;onAvatar:()=>void;onQuestion:()=>void;onExam:()=>void;onReading:()=>void;onActivity:()=>void;onPlan:()=>void;onProgress:()=>void}){
 const recordButton=useRef<HTMLButtonElement>(null);const close=()=>{setChoose(false);recordButton.current?.focus()};const [choose,setChoose]=useState(false),sid=student.id,plan=daySchedules(state.schedules,sid,date,'Haftalık',state.holidays||[]),holiday=state.holidays?.find(h=>h.studentId===sid&&h.date===date),recent=state.logs.filter(x=>x.studentId===sid&&x.date<=date).sort((a,b)=>b.date.localeCompare(a.date))[0],book=state.books.find(b=>b.id===recent?.bookId),reading=state.reading?.find(b=>b.studentId===sid&&b.status==='Okuyorum'),bounds=periodBounds(date,'Haftalık'),days=new Set([...state.logs,...state.activities].filter(x=>x.studentId===sid&&x.date>=bounds[0]&&x.date<=date).map(x=>x.date)).size;
 const actions=[{label:'Soru çözdüm',detail:'Kaynak ve soru sonucunu ekle',icon:PenLine,run:onQuestion},{label:'Deneme yaptım',detail:'Deneme sonucunu kaydet',icon:ClipboardList,run:onExam},{label:'Kitap okudum',detail:'Okuduğun sayfayı güncelle',icon:BookOpen,run:onReading},{label:'Konu çalıştım',detail:'Tekrar veya öğrenme süreni ekle',icon:Check,run:onActivity}];
 return <div className="simpleStudentHome"><div className="homeWelcome"><div><p>{student.grade}. sınıf · {new Date(date+'T12:00:00Z').toLocaleDateString('tr-TR',{day:'numeric',month:'long'})}</p><h1>Merhaba {student.name.split(' ')[0]}</h1></div></div><HomeInspiration student={student} exams={state.exams} days={days} celebrateId={celebrateId} recordRef={recordButton} onRecord={()=>setChoose(true)} onAvatar={onAvatar} onProgress={onProgress}/><section className="homeSection"><div className="homeSectionHead"><h2>Bugünkü planım</h2><button className="textButton" onClick={onPlan}>Planın tamamı</button></div>{holiday?<p className="homeQuiet">{holiday.label} · Bugün dinlenmeye yer var.</p>:plan.length?<ol className="homePlan">{plan.slice(0,3).map(s=><li key={s.id}><span>{s.time}–{scheduleEnd(s)}</span><strong>{s.activity}</strong></li>)}</ol>:<div className="homeEmpty"><CalendarDays size={22}/><p>Bugün için plan yok.</p><button className="textButton" onClick={onPlan}>Planımı oluştur</button></div>}<small>Bu liste planladığın aktiviteleri gösterir.</small></section><section className="homeSection"><div className="homeSectionHead"><h2>Kaldığım yer</h2></div>{recent?<div className="homeContinue"><div><span>Son soru çalışmam</span><strong>{recent.subject} · {recent.topic}</strong><p>{book?.name||'Kaynak belirtilmedi'}</p></div><button className="secondary" onClick={onQuestion}>Çalışma ekle</button></div>:<p className="homeQuiet">İlk çalışmanı kaydettiğinde burada görebilirsin.</p>}{reading&&<div className="homeContinue homeReading"><div><span>Okuduğum kitap</span><strong>{reading.title}</strong><p>{reading.currentPage} / {reading.totalPages} sayfa</p></div><button className="textButton" onClick={onReading}>Sayfamı güncelle</button></div>}</section>{choose&&<div className="modalOverlay" onClick={e=>{if(e.target===e.currentTarget)close()}} onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('button')),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><section className="modal homeChooser" role="dialog" aria-modal="true" aria-labelledby="home-chooser-title"><div className="modalHeader"><h2 id="home-chooser-title">Ne yaptın?</h2><button className="iconButton" onClick={close} aria-label="Pencereyi kapat" autoFocus><X/></button></div><div className="homeChoices">{actions.map(a=><button key={a.label} onClick={()=>{setChoose(false);a.run()}}><a.icon size={24}/><span><strong>{a.label}</strong><small>{a.detail}</small></span></button>)}</div></section></div>}</div>
}
