'use client';
import {useState} from 'react';
import {PlayCircle,Plus,Search} from 'lucide-react';
import type {Activity,ClassVideo} from '../lib/model';
import {videoChannels,videoSubject,savedVideoLinks} from '../lib/videos';
import {questionSubjects} from '../lib/curriculum';
export default function VideoSources({activities,grade,onAdd,shared=[]}:{activities:Activity[];grade:number;onAdd:(channelId:string)=>void;shared?:ClassVideo[]}){
 const [filter,setFilter]=useState(''),[search,setSearch]=useState('');
 const query=search.trim().toLocaleLowerCase('tr'),watching=activities.filter(a=>a.kind==='Video İzleme'),saved=savedVideoLinks(watching).filter(v=>!shared.some(s=>s.url===v.url)),channels=videoChannels.filter(c=>(!filter||videoSubject(c.subject,grade)===filter)&&(!query||c.name.toLocaleLowerCase('tr').includes(query)));
 return <section className="videoLibrary"><div className="videoLibraryHeading"><div><h2>Ders kanalları</h2><p>Daha önce eklenen {videoChannels.length} kanal burada.</p></div><span className="badge">{channels.length} kanal</span></div><div className="toolbar videoLibraryFilters"><label className="videoSearch"><Search size={18}/><input aria-label="Video kanalı ara" placeholder="Kanal ara…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Video kaynakları ders filtresi" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tüm dersler</option>{questionSubjects(grade).map(s=><option key={s}>{s}</option>)}</select></div><p className="videoLibraryHint">Kanal bağlantıları YouTube aramasını açar. Sınıfına ve konuna uygun videoyu seç.</p><div className="videoChannelGrid">{channels.map(c=><article className="videoChannelCard" key={c.id}><div className="videoChannelTop"><span className="videoSymbol"><PlayCircle size={24}/></span><span className="badge">{videoSubject(c.subject,grade)}</span></div><h3>{c.name}</h3><div className="videoChannelActions"><a href={c.searchUrl} target="_blank" rel="noopener noreferrer" className="secondary">YouTube’da ara</a><button className="textButton" onClick={()=>onAdd(c.id)}><Plus size={16}/>İzleme kaydet</button></div></article>)}</div>{!channels.length&&<p className="empty">Bu filtrede kanal yok. Aramayı veya ders seçimini değiştir.</p>}{saved.length>0&&<section className="savedVideoSection"><div className="videoLibraryHeading"><div><h2>Önceden kaydedilen videolar</h2><p>Seçili öğrencinin izleme kayıtlarındaki bağlantılar.</p></div><span className="badge">{saved.length}</span></div><div className="resourceList">{saved.map(v=><article key={v.url} className="resourceListItem"><span className="resourceListIcon"><PlayCircle size={22}/></span><div className="resourceListInfo"><h3>{v.title}</h3><p>{v.subject} · {v.channel} · {v.minutes} dk</p></div><a className="secondary" href={v.url} target="_blank" rel="noopener noreferrer">Videoyu aç</a></article>)}</div></section>}<details className="studyExtras videoHistory"><summary>İzleme geçmişi · {watching.length} kayıt · {watching.reduce((n,a)=>n+a.minutes,0)} dakika</summary>{watching.length?<div className="tableWrap"><table><thead><tr><th>Tarih</th><th>Kanal</th><th>Ders / konu</th><th>Süre</th><th>Video</th></tr></thead><tbody>{[...watching].sort((a,b)=>b.date.localeCompare(a.date)).map(a=><tr key={a.id}><td>{new Date(a.date+'T12:00:00Z').toLocaleDateString('tr-TR',{day:'numeric',month:'short'})}</td><td>{videoChannels.find(c=>c.id===a.channelId)?.name||'Kanal'}</td><td><strong>{a.subject}</strong><small className="cellNote">{a.topic}</small></td><td>{a.minutes} dk</td><td>{savedVideoLinks([a])[0]?<a href={a.videoUrl} target="_blank" rel="noopener noreferrer">Videoyu aç</a>:'—'}</td></tr>)}</tbody></table></div>:<p className="muted">İzlediğin konu ve süreyi kaydettiğinde burada görebilirsin.</p>}</details></section>
}
