'use client';
import {useState} from 'react';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import type {Log,Exam} from '../lib/model';
import {today,summarize} from '../lib/model';
import {weeklyData,weeklyWindow,shiftDate,examGroups,examAverage,countChange} from '../lib/comparison';
const f=(n:number)=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(n);
const sign=(n:number)=>(n>0?'+':'')+f(n);
const dateLabel=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('tr-TR',{day:'numeric',month:'short'});
const within=(date:string,start:string,end:string)=>date>=start&&date<=end;
function Change({before,now,valid,percentage=false}:{before:number|null;now:number|null;valid:boolean;percentage?:boolean}){if(!valid||before===null||now===null)return <span className="muted">Karşılaştırma için veri yok</span>;const d=now-before;return <span className={d>0?'change positive':d<0?'change negative':'change neutral'}>{sign(d)}{percentage?' yüzde puan':''}</span>}
function CountDelta({before,now,valid}:{before:number;now:number;valid:boolean}){const d=countChange(before,now,valid,valid);if(!d)return <span className="muted">Karşılaştırma için veri yok</span>;return <span className={d.absolute>0?'change positive':d.absolute<0?'change negative':'change neutral'}>{sign(d.absolute)}{d.percent!==null?` / %${sign(d.percent)}`:''}</span>}
export default function WeeklyComparison({logs,exams,subjects,date,asOfDate,children,afterTrend}:{logs:Log[];exams:Exam[];subjects:string[];date:string;asOfDate?:string;children?:React.ReactNode;afterTrend?:React.ReactNode}){
 const asOf=asOfDate||today(),data=weeklyData(logs,date,asOf),w=data.window,{now,before}=data;const valid=now.questions>0&&before.questions>0;const groups=examGroups(exams);const [selectedGroup,setSelectedGroup]=useState('');const activeGroup=groups.find(g=>g.key===selectedGroup)||groups[0];
 const rows=['Toplam',...subjects].map(subject=>({subject,now:summarize(subject==='Toplam'?data.current:data.current.filter(x=>x.subject===subject)),before:summarize(subject==='Toplam'?data.previous:data.previous.filter(x=>x.subject===subject))}));
 const comparisonGroups=groups.map(g=>({...g,current:w.future?[]:g.exams.filter(e=>within(e.date,w.start,w.currentEnd)),previous:w.future?[]:g.exams.filter(e=>within(e.date,w.previousStart,w.previousEnd))})).filter(g=>g.current.length||g.previous.length);
 const chartData=Array.from({length:8},(_,i)=>{const start=shiftDate(w.start,(i-7)*7),win=weeklyWindow(start,asOf),items=win.future?[]:logs.filter(x=>within(x.date,start,win.currentEnd)),a=summarize(items),es=win.future?[]:(activeGroup?.exams||[]).filter(e=>within(e.date,start,win.currentEnd));return{label:dateLabel(start)+(win.partial?'*':''),questions:win.future?null:a.questions,accuracy:a.accuracy,net:examAverage(es),partial:win.partial}});
 const notes:string[]=[];
 if(w.future)notes.push('Seçili hafta henüz başlamadı. Karşılaştırma için veri yok.');
 else if(!valid)notes.push(`${!before.questions?'Önceki':'Seçili'} haftada soru çözüm kaydı yok. Kayıt olmaması çalışma yapılmadığını göstermez; miktar ve doğruluk değişimi hesaplanmadı.`);
 else{
 const d=countChange(before.questions,now.questions,true,true)!;
 notes.push(`Soru sayısı ${before.questions} → ${now.questions}. ${d.absolute>0?`Çalışma miktarı ${f(d.absolute)} soru (%${f(d.percent!)}) arttı.`:d.absolute<0?`Kaydedilen çalışma miktarı ${f(-d.absolute)} soru (%${f(-d.percent!)}) azaldı.`:'Kaydedilen soru sayısı aynı kaldı.'}`);
 const accuracyDelta=now.accuracy!-before.accuracy!,correctDelta=now.correct-before.correct;
 notes.push(`Doğru adedi ${before.correct} → ${now.correct} (${sign(correctDelta)}). Doğruluk %${f(before.accuracy!)} → %${f(now.accuracy!)}; ${accuracyDelta>0?`${f(accuracyDelta)} yüzde puan yükseldi`:accuracyDelta<0?`${f(-accuracyDelta)} yüzde puan düştü`:'aynı kaldı'}.`);
 const expected=now.questions*before.accuracy!/100,diff=now.correct-expected;
 notes.push(`Önceki doğruluk oranı bu haftanın ${now.questions} sorusunda korunsaydı ${f(expected)} doğru beklenirdi. Gerçekleşen ${now.correct} doğru, bu seviyenin ${f(Math.abs(diff))} ${diff>=0?'üzerinde':'altında'}. Bu hesap kaynak veya test zorluğunun aynı olduğunu varsaymaz.`);
 if(now.wrong>before.wrong&&now.wrong/now.questions<before.wrong/before.questions)notes.push(`Yanlış adedi arttı, ancak yanlış oranı %${f(before.wrong/before.questions*100)}’den %${f(now.wrong/now.questions*100)}’e düştü. Yalnızca yanlış adedine göre olumsuz değerlendirme yapılmaz.`);
 if(now.questions<20||before.questions<20)notes.push('Haftalardan en az birinde 20’den az soru var; doğruluk değişimi sınırlı bir örnekleme dayanıyor.');
 }
 for(const g of comparisonGroups){if(!g.current.length||!g.previous.length)continue;const a=examAverage(g.current)!,b=examAverage(g.previous)!;notes.push(`${g.label}: ortalama net ${f(b)} → ${f(a)} (${sign(a-b)} net). ${!g.sample.difficulty||g.sample.difficulty==='Belirtilmedi'?'Zorluk bilgisi yok; değişimi eşdeğer sınavlarda ölçülmüş bir kazanım olarak yorumlamayın.':'Zorluk etiketi kullanıcı tarafından girilir; aynı etiket sınavların tamamen eşdeğer olduğunu kanıtlamaz.'}`)}
 if(!comparisonGroups.some(g=>g.current.length&&g.previous.length))notes.push('Aynı kapsam, soru dağılımı ve zorluk etiketinde iki haftaya ait deneme kaydı yok. Net karşılaştırması için veri yok.');
 return <section className="weeklyComparison">
 <div className="trendChartHeading"><h2>8 haftalık gelişim</h2><p>Geçmiş haftalar tam dönemdir. * işaretli hafta devam ediyor; henüz tamamlanmış değildir.</p></div><div className="trendChartGrid">{[{key:'questions',title:'Çözülen soru',color:'#245de4',unit:'soru',domain:undefined},{key:'accuracy',title:'Doğruluk oranı',color:'#087c63',unit:'%',domain:[0,100]},{key:'net',title:'Ortalama deneme neti',color:'#9b4ed5',unit:'net',domain:undefined}].map(c=><section className="panel trendChart" key={c.key}><h3>{c.title}</h3>{c.key==='net'&&groups.length>0&&<select aria-label="Net grafiği deneme kapsamı" value={activeGroup?.key||''} onChange={e=>setSelectedGroup(e.target.value)}>{groups.map(g=><option key={g.key} value={g.key}>{g.label}</option>)}</select>}{chartData.some(x=>x[c.key as 'questions'|'accuracy'|'net']!==null)?<div className="chartCanvas"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:300,height:210}}><LineChart data={chartData} margin={{top:12,right:10,bottom:4,left:-13}}><CartesianGrid vertical={false} stroke="#e5eaf3"/><XAxis dataKey="label" tick={{fontSize:12,fill:'#6b778c'}} axisLine={false} tickLine={false} interval="preserveStartEnd"/><YAxis domain={c.domain} tick={{fontSize:12,fill:'#6b778c'}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[v===null?'Kayıt yok':f(Number(v)),c.title]} contentStyle={{fontSize:13,borderRadius:8}}/><Line type="linear" dataKey={c.key} stroke={c.color} strokeWidth={2.5} dot={{r:4}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>:<div className="chartNoData">Grafik için kayıt yok.</div>}<small>{c.key==='questions'?'0, o haftaya soru kaydı girilmediğini gösterir.':c.key==='accuracy'?'Kayıtsız haftalar boş bırakılır; oranlar toplam doğru / toplam sorudur.':'Yalnızca seçili kapsam ve soru dağılımındaki denemeler gösterilir.'}</small></section>)}</div>
 {children}
 <section className="panel trendSummary"><div className="panelHead"><h2>Haftalık trend özeti</h2></div><div className="trendNotes">{notes.map((note,i)=><p key={i}>{note}</p>)}</div><div className="subjectTrendNotes">{rows.filter(r=>r.subject!=='Toplam'&&r.now.questions&&r.before.questions).map(r=><p key={r.subject}><strong>{r.subject}:</strong> {r.before.questions} → {r.now.questions} soru; doğru {r.before.correct} → {r.now.correct}; doğruluk %{f(r.before.accuracy!)} → %{f(r.now.accuracy!)}.</p>)}</div></section>
 {afterTrend}
<div className="comparisonIntro"><div><span className="eyebrow">HAFTALIK GELİŞİM</span><h2>Geçen haftaya göre durum</h2></div><span className="badge">{w.future?'Gelecek hafta':w.partial?'Aynı günlere kadar':'Tam hafta karşılaştırması'}</span></div><div className="comparisonDates"><span><strong>Önceki hafta</strong>{dateLabel(w.previousStart)} – {dateLabel(w.previousEnd)}</span><span><strong>Seçili hafta</strong>{dateLabel(w.start)} – {dateLabel(w.future?w.end:w.currentEnd)}</span></div>{w.partial&&<div className="info">Devam eden hafta, önceki haftanın aynı gününe kadar karşılaştırılır. Bugün girilen kayıtlar henüz tamamlanmamış olabilir.</div>}
 <section className="panel"><div className="panelHead"><h2><span className="comparisonNumber">1</span>Çalışma miktarı</h2><span className="muted">Deneme soruları bu toplama dahil değildir</span></div><div className="tableWrap"><table><thead><tr><th>Ders</th><th>Önceki hafta</th><th>Seçili hafta</th><th>Değişim</th></tr></thead><tbody>{rows.map(r=><tr key={r.subject}><td><strong>{r.subject}</strong></td><td>{r.before.questions} soru</td><td>{r.now.questions} soru</td><td><CountDelta before={r.before.questions} now={r.now.questions} valid={r.before.questions>0&&r.now.questions>0}/></td></tr>)}</tbody></table></div></section>
 <section className="panel"><div className="panelHead"><h2><span className="comparisonNumber">2</span>Doğru sayısı ve doğruluk oranı</h2><span className="muted">Doğru / toplam soru</span></div><div className="tableWrap"><table><thead><tr><th>Ders</th><th>Önceki D / Y / B</th><th>Seçili D / Y / B</th><th>Doğru adedi değişimi</th><th>Doğruluk</th><th>Oran değişimi</th></tr></thead><tbody>{rows.map(r=><tr key={r.subject}><td><strong>{r.subject}</strong></td><td>{r.before.correct} / {r.before.wrong} / {r.before.blank}</td><td>{r.now.correct} / {r.now.wrong} / {r.now.blank}</td><td><Change before={r.before.correct} now={r.now.correct} valid={r.before.questions>0&&r.now.questions>0}/></td><td><span className="ratioPair">{r.before.accuracy===null?'—':'%'+f(r.before.accuracy)} <span>→</span> {r.now.accuracy===null?'—':'%'+f(r.now.accuracy)}</span></td><td><Change before={r.before.accuracy} now={r.now.accuracy} valid={r.before.questions>0&&r.now.questions>0} percentage/></td></tr>)}</tbody></table></div></section>
 <section className="panel"><div className="panelHead"><h2><span className="comparisonNumber">3</span>Deneme neti</h2><span className="muted">Birden fazla deneme varsa ortalama net</span></div>{comparisonGroups.length?<div className="tableWrap"><table><thead><tr><th>Deneme kapsamı / ders</th><th>Önceki hafta</th><th>Seçili hafta</th><th>Net değişimi</th></tr></thead><tbody>{comparisonGroups.flatMap(g=>['Toplam',...g.sample.rows.map(r=>r.subject)].map(sub=>{const a=examAverage(g.current,sub==='Toplam'?undefined:sub),b=examAverage(g.previous,sub==='Toplam'?undefined:sub);return <tr key={g.key+sub}><td><strong>{sub}</strong><small className="cellNote">{g.label}</small></td><td>{b===null?'Kayıt yok':f(b)+' net'}<small className="cellNote muted">{g.previous.length} deneme</small></td><td>{a===null?'Kayıt yok':f(a)+' net'}<small className="cellNote muted">{g.current.length} deneme</small></td><td><Change before={b} now={a} valid={a!==null&&b!==null}/></td></tr>}))}</tbody></table></div>:<p className="panelText muted">Karşılaştırma için veri yok. Seçili veya önceki haftaya ait deneme kaydı bulunamadı.</p>}<p className="comparisonCaveat">Tam ve branş denemeleri; ders kapsamı, soru sayıları ve zorluk etiketi farklıysa ayrı gösterilir. Zorluğu belirtilmeyen denemeler eşdeğer kabul edilmez.</p></section>
 </section>;
}
