import {net,total,summarize,type State} from './model';
import {readingStats,scheduleEnd,scheduleDays} from './planning';
type Cell=string|number|{date:string}|null;
type Sheet={name:string;head:string[];rows:Cell[][]};
const xml=(v:unknown)=>String(v??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const col=(n:number):string=>n<26?String.fromCharCode(65+n):col(Math.floor(n/26)-1)+String.fromCharCode(65+n%26);
const date=(v:string):Cell=>v?{date:v}:null;
// Uncompressed ZIP keeps the browser exporter dependency-free and uses standard OOXML.
function zip(files:Record<string,string>):Uint8Array{const enc=new TextEncoder(),parts:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;const crc=(a:Uint8Array)=>{let c=0xffffffff;for(const b of a){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0};const header=(size:number)=>{const a=new Uint8Array(size);return{a,v:new DataView(a.buffer)}};for(const [name,body]of Object.entries(files)){const n=enc.encode(name),data=enc.encode(body),sum=crc(data),h=header(30);h.v.setUint32(0,0x04034b50,true);h.v.setUint16(4,20,true);h.v.setUint32(14,sum,true);h.v.setUint32(18,data.length,true);h.v.setUint32(22,data.length,true);h.v.setUint16(26,n.length,true);parts.push(h.a,n,data);const c=header(46);c.v.setUint32(0,0x02014b50,true);c.v.setUint16(4,20,true);c.v.setUint16(6,20,true);c.v.setUint32(16,sum,true);c.v.setUint32(20,data.length,true);c.v.setUint32(24,data.length,true);c.v.setUint16(28,n.length,true);c.v.setUint32(42,offset,true);central.push(c.a,n);offset+=30+n.length+data.length}const size=central.reduce((s,a)=>s+a.length,0),end=header(22);end.v.setUint32(0,0x06054b50,true);end.v.setUint16(8,Object.keys(files).length,true);end.v.setUint16(10,Object.keys(files).length,true);end.v.setUint32(12,size,true);end.v.setUint32(16,offset,true);const out=new Uint8Array(offset+size+22);let at=0;for(const a of [...parts,...central,end.a]){out.set(a,at);at+=a.length}return out}
export function buildExcel(state:State,sid:string|null,reference:string):Uint8Array{
 const students=state.students.filter(s=>!sid||s.id===sid),ids=new Set(students.map(s=>s.id)),name=(id:string)=>students.find(s=>s.id===id)?.name||id;
 const logs=state.logs.filter(x=>ids.has(x.studentId)),exams=state.exams.filter(x=>ids.has(x.studentId));
 const sheets:Sheet[]=[
 {name:'Özet',head:['Öğrenci','Sınıf','Referans tarihi','Soru','Doğru','Yanlış','Boş','Doğruluk','Çalışılan gün','Deneme','Bu hafta okunan kitap','Bu ay okunan kitap','Bu yıl okunan kitap'],rows:students.map(s=>{const a=summarize(logs.filter(l=>l.studentId===s.id)),r=readingStats((state.reading||[]).filter(b=>b.studentId===s.id),reference);return[s.name,s.grade,date(reference),a.questions,a.correct,a.wrong,a.blank,a.accuracy===null?null:a.accuracy/100,a.days,exams.filter(e=>e.studentId===s.id).length,r.week.length,r.month.length,r.year.length]})},
 {name:'Soru çalışmaları',head:['Öğrenci','Tarih','Ders','Konu','Kaynak','Test','Toplam soru','Doğru','Yanlış','Boş','Süre (dk)','Not'],rows:logs.map(l=>[name(l.studentId),date(l.date),l.subject,l.topic,state.books.find(b=>b.id===l.bookId)?.name||'Belirtilmemiş',l.testLabel||'',total(l),l.correct,l.wrong,l.blank,l.minutes,l.note])},
 {name:'Denemeler',head:['Öğrenci','Tarih','Deneme','Tür','Zorluk','Puan','Ders','Soru','Doğru','Yanlış','Boş','Net'],rows:exams.flatMap(e=>e.rows.map(r=>[name(e.studentId),date(e.date),e.name,e.type,e.difficulty||'Belirtilmedi',e.score?Number(e.score):null,r.subject,r.total,r.correct,r.wrong,r.blank,net(r)]))},
 {name:'Aktiviteler',head:['Öğrenci','Tarih','Aktivite','Ders','Konu','Süre (dk)','Sayfa','Not'],rows:state.activities.filter(a=>ids.has(a.studentId)).map(a=>[name(a.studentId),date(a.date),a.kind,a.subject||'',a.topic||'',a.minutes,a.pages,a.note])},
 {name:'Plan',head:['Öğrenci','Plan türü','Günler','Tarih','Başlangıç saati','Bitiş saati','Aktivite','Tekrar başlangıcı','Tekrar bitişi'],rows:state.schedules.filter(s=>ids.has(s.studentId)).map(s=>[name(s.studentId),s.type,scheduleDays(s).map(d=>['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'][d]).join(', '),date(s.date||''),s.time,scheduleEnd(s),s.activity,date(s.repeatStart||''),date(s.repeatEnd||'')])},
 {name:'Tatil günleri',head:['Öğrenci','Tarih','Açıklama'],rows:(state.holidays||[]).filter(h=>ids.has(h.studentId)).map(h=>[name(h.studentId),date(h.date),h.label])},
 {name:'Okuma listesi',head:['Öğrenci','Kitap','Yazar','Toplam sayfa','Okunan sayfa','Durum','Başlangıç','Bitiş','Takvim günü','Not'],rows:(state.reading||[]).filter(b=>ids.has(b.studentId)).map(b=>[name(b.studentId),b.title,b.author,b.totalPages,b.currentPage,b.status,date(b.started),date(b.finished),b.started&&b.finished?Math.floor((Date.parse(b.finished)-Date.parse(b.started))/86400000)+1:null,b.note])},
 {name:'Kaynaklar',head:['Öğrenci','Kaynak','Yayınevi','Sınıf','Ders','Tür','Bağlantı'],rows:students.flatMap(s=>state.books.filter(b=>b.studentIds.includes(s.id)).map(b=>[s.name,b.name,b.publisher,b.grade,b.subject,b.type,b.url]))},
 {name:'Hedefler',head:['Öğrenci','Ders','Haftalık soru hedefi','Doğruluk hedefi'],rows:state.goals.filter(g=>ids.has(g.studentId)).map(g=>[name(g.studentId),g.subject,g.weekly,g.accuracy/100])},
 {name:'Öğretmen notları',head:['Öğrenci','Dönem','Tarih','Not'],rows:state.reviews.filter(r=>ids.has(r.studentId)).map(r=>[name(r.studentId),r.period,date(r.date),r.note])}
 ];
 const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rels='http://schemas.openxmlformats.org/package/2006/relationships';
 const files:Record<string,string>={
 '[Content_Types].xml':`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`,
 '_rels/.rels':`<Relationships xmlns="${rels}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
 'xl/workbook.xml':`<workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`,
 'xl/_rels/workbook.xml.rels':`<Relationships xmlns="${rels}">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="styles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`,
 'xl/styles.xml':`<styleSheet xmlns="${ns}"><numFmts count="1"><numFmt numFmtId="164" formatCode="dd/mm/yyyy"/></numFmts><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF244BB4"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="5"><xf fontId="0" fillId="0" borderId="0" xfId="0"/><xf fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="center"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="10" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="2" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`};
 for(const [i,s]of sheets.entries()){const rows=[s.head,...s.rows];files[`xl/worksheets/sheet${i+1}.xml`]=`<worksheet xmlns="${ns}"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${s.head.map((h,j)=>`<col min="${j+1}" max="${j+1}" width="${Math.min(55,Math.max(15,h.length+3,...s.rows.map(r=>typeof r[j]==='string'?Math.min(45,String(r[j]).length+2):15)))}" customWidth="1"/>`).join('')}</cols><sheetData>${rows.map((row,r)=>`<row r="${r+1}"${r===0?' ht="36" customHeight="1"':''}>${row.map((v,c)=>{const ref=col(c)+(r+1);if(v===null)return`<c r="${ref}"/>`;if(typeof v==='object'){const n=Math.round(Date.parse(v.date)/86400000)+25569;return`<c r="${ref}" s="2"><v>${n}</v></c>`}if(typeof v==='number'){const percentage=(i===0&&c===7)||(i===8&&c===3);return`<c r="${ref}" s="${percentage?3:i===2&&c===11?4:0}"><v>${Number.isFinite(v)?v:0}</v></c>`}return`<c r="${ref}" s="${r===0?1:0}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`}).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${col(s.head.length-1)}${rows.length}"/></worksheet>`}return zip(files)
}
export function downloadExcel(state:State,sid:string|null,reference:string){const bytes=buildExcel(state,sid,reference),url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download=`LGS-Pusula-${sid||'tum-ogrenciler'}-${reference}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
