import {uniqueStudies} from './study';
import type {Schedule,ReadingBook,State,Student} from './model';
import {periodBounds} from './model';
export const planActivities=['Okul','Dinlenme / Yemek','Dinlenme','Yemek','Ödev / Tekrar','Ödev','Konu Tekrarı','Spor','Matematik','Deneme','Türkçe','Fen','Sosyal Bilgiler','İnkılap Tarihi','İngilizce','Din','Serbest Zaman','Kitap Okuma','Uyku','Diğer'];
export const minutes=(time:string)=>{const [h,m]=time.split(':').map(Number);return h*60+m};
export const clock=(n:number)=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
export const scheduleEnd=(s:Schedule)=>s.endTime||clock(Math.min(1439,minutes(s.time)+45));
export const weekday=(date:string)=>(new Date(date+'T12:00:00Z').getUTCDay()+6)%7;
export const scheduleDays=(s:Schedule)=>s.weekdays||[s.day];
export function occursOn(s:Schedule,date:string,type='Haftalık'){return s.date?s.date===date:s.type===type&&scheduleDays(s).includes(weekday(date))&&(!s.repeatStart||date>=s.repeatStart)&&(!s.repeatEnd||date<=s.repeatEnd);}
export function daySchedules(schedules:Schedule[],studentId:string,date:string,type='Haftalık',holidays:{studentId:string;date:string}[]=[]){if(holidays.some(h=>h.studentId===studentId&&h.date===date))return [];return schedules.filter(s=>s.studentId===studentId&&occursOn(s,date,type)).sort((a,b)=>a.time.localeCompare(b.time));}
export function clashes(a:Schedule,b:Schedule){if(a.studentId!==b.studentId||a.id===b.id)return false;let same=false;if(a.date&&b.date)same=a.date===b.date;else if(a.date)same=occursOn(b,a.date,b.type);else if(b.date)same=occursOn(a,b.date,a.type);else if(a.type===b.type){const from=[a.repeatStart||'0001-01-01',b.repeatStart||'0001-01-01'].sort()[1],to=[a.repeatEnd||'9999-12-31',b.repeatEnd||'9999-12-31'].sort()[0];same=from<=to&&scheduleDays(a).some(d=>scheduleDays(b).includes(d)&&(()=>{const first=new Date(from+'T12:00:00Z');first.setUTCDate(first.getUTCDate()+(d-weekday(from)+7)%7);return first.toISOString().slice(0,10)<=to})());}return same&&minutes(a.time)<minutes(scheduleEnd(b))&&minutes(b.time)<minutes(scheduleEnd(a));}
export function monthDates(date:string){const d=new Date(date+'T12:00:00Z'),first=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1,12)),last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0,12));first.setUTCDate(first.getUTCDate()-(first.getUTCDay()+6)%7);const size=Math.ceil(((last.getTime()-first.getTime())/86400000+1)/7)*7;return Array.from({length:size},(_,i)=>{const x=new Date(first);x.setUTCDate(x.getUTCDate()+i);return x.toISOString().slice(0,10)});}
export function validDate(d:string){return /^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d+'T12:00:00Z').toISOString().slice(0,10)===d;}
export function validSchedule(s:Schedule){return ['Haftalık','Sömestr','Tarihli'].includes(s.type)&&Number.isInteger(s.day)&&s.day>=0&&s.day<=6&&typeof s.activity==='string'&&!!s.activity.trim()&&s.activity.length<=150&&/^([01]\d|2[0-3]):[0-5]\d$/.test(s.time)&&(!s.endTime||/^([01]\d|2[0-3]):[0-5]\d$/.test(s.endTime))&&minutes(scheduleEnd(s))>minutes(s.time)&&(!s.date||validDate(s.date))&&(s.type!=='Tarihli'||!!s.date)&&(!s.weekdays||(Array.isArray(s.weekdays)&&s.weekdays.length>0&&s.weekdays.length<=7&&new Set(s.weekdays).size===s.weekdays.length&&s.weekdays.every(d=>Number.isInteger(d)&&d>=0&&d<=6)&&!s.date))&&(!s.repeatStart||validDate(s.repeatStart))&&(!s.repeatEnd||validDate(s.repeatEnd))&&(!s.repeatStart||!s.repeatEnd||s.repeatEnd>=s.repeatStart);}
export function validReading(b:ReadingBook){return (b.recommendationId===undefined||typeof b.recommendationId==='string'&&b.recommendationId.length<=200)&&!!b.title?.trim()&&b.title.length<=200&&typeof b.author==='string'&&b.author.length<=150&&Number.isInteger(b.totalPages)&&b.totalPages>0&&b.totalPages<=100000&&Number.isInteger(b.currentPage)&&b.currentPage>=0&&b.currentPage<=b.totalPages&&['Listemde','Okuyorum','Bitirdim'].includes(b.status)&&(!b.started||validDate(b.started))&&(!b.finished||validDate(b.finished))&&(b.status!=='Okuyorum'||!!b.started)&&(b.status!=='Bitirdim'||(!!b.started&&!!b.finished&&b.currentPage===b.totalPages))&&(!b.finished||!!b.started&&b.finished>=b.started)&&typeof b.note==='string'&&b.note.length<=2000;}
export function readingDays(b:ReadingBook,asOf:string){if(!b.started)return null;const end=b.finished||asOf;return end<b.started?null:Math.round((Date.parse(end+'T12:00:00Z')-Date.parse(b.started+'T12:00:00Z'))/86400000)+1;}
export function readingStats(books:ReadingBook[],date:string){const week=periodBounds(date,'Haftalık'),month=periodBounds(date,'Aylık'),year=[date.slice(0,4)+'-01-01',date.slice(0,4)+'-12-31'];const completed=books.filter(b=>b.status==='Bitirdim'&&b.finished&&b.finished<=date);const inRange=(r:string[])=>completed.filter(b=>b.finished!>=r[0]&&b.finished!<=r[1]);return{week:inRange(week),month:inRange(month),year:inRange(year),current:books.filter(b=>b.status==='Okuyorum')};}
const demoReading:ReadingBook[]=['deniz','ece','mert','selin'].flatMap((studentId,i)=>[
{id:`${studentId}-read-1`,studentId,title:'Yıldızlara Açılan Kapı',author:'Demo yazar',totalPages:160+i*16,currentPage:72+i*8,status:'Okuyorum' as const,started:'2026-10-01',finished:'',note:'Örnek okuma kaydı'},
{id:`${studentId}-read-2`,studentId,title:'Ormanın Gizli Haritası',author:'Demo yazar',totalPages:128,currentPage:128,status:'Bitirdim' as const,started:'2026-09-23',finished:'2026-10-06',note:'En sevdiğim bölüm son keşifti.'},
{id:`${studentId}-read-3`,studentId,title:'Denizde Bir Yaz',author:'Demo yazar',totalPages:144,currentPage:144,status:'Bitirdim' as const,started:'2026-09-04',finished:'2026-09-20',note:''},
{id:`${studentId}-read-4`,studentId,title:'Bir Robotun Günlüğü',author:'Demo yazar',totalPages:192,currentPage:0,status:'Listemde' as const,started:'',finished:'',note:'Sıradaki kitabım'}]);
export function normalizeState(state:State):State{
 const demoIds=new Set(state.students.filter(s=>[['deniz','Deniz Aras'],['ece','Ece Demir'],['mert','Mert Kaya'],['selin','Selin Yılmaz']].some(([id,name])=>s.id===id&&s.name===name)).map(s=>s.id));
 const demoDefaults:Record<string,Partial<Student>>={deniz:{avatarId:'fox',journey:'rocket'},ece:{avatarId:'penguin',journey:'sail'},mert:{avatarId:'robot',journey:'fireworks'},selin:{avatarId:'owl',journey:'star',extraCourses:['Almanca'],disabledCourses:['İngilizce'],courseTopics:{Almanca:['Selamlaşma','Kendini tanıtma','Günlük rutinler']}}};
 const students=state.students.map(s=>demoIds.has(s.id)?{avatarChosen:true,gradeConfirmed:true,...demoDefaults[s.id],...s}:s);
 const readingRecommendations=state.readingRecommendations??(demoIds.size?[{id:'demo-reading-stars',title:'Gökyüzünün Gizli Haritası',author:'Demo yazar',totalPages:160,grades:[6,7]},{id:'demo-reading-journey',title:'Bir Yolculuk Bin Keşif',author:'Demo yazar',totalPages:192,grades:[7,8]}]:[]);
 const sharedIds=new Set(!state.books.some(b=>b.shared!==undefined)&&demoIds.size?[6,7,8].map(g=>state.books.find(b=>b.grade===g&&b.subject==='Matematik')?.id).filter(Boolean):[]);
 const books=state.books.map(b=>sharedIds.has(b.id)?{...b,shared:true,grades:[b.grade]}:b);
 const schedules=[...state.schedules];
 for(const sid of demoIds){const legacy=state.schedules.filter(s=>s.studentId===sid);if(legacy.length&&!legacy.some(s=>s.endTime||s.date)){
  for(let day=0;day<5;day++){for(const [time,endTime,activity] of [['08:00','15:00','Okul'],['15:00','17:30','Dinlenme / Yemek'],['17:30','18:00','Ödev / Tekrar']]){const block:Schedule={id:`${sid}-school-day-${day}-${time}`,studentId:sid,type:'Haftalık',day,time,endTime,activity};if(!schedules.some(s=>clashes(block,s)))schedules.push(block);}}
  for(let i=0;i<schedules.length;i++)if(schedules[i].studentId===sid&&!schedules[i].endTime)schedules[i]={...schedules[i],endTime:scheduleEnd(schedules[i])};
 }}
 return uniqueStudies({...state,students,books,readingRecommendations,schedules,reading:state.reading??demoReading.filter(b=>demoIds.has(b.studentId)),holidays:state.holidays??[]});
}
